name: Build Check

# this so that this runs on every PR
on:
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      # setup pnpm
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      # install deps    
      - name: Install dependencies
        run: pnpm install
      # run build  
      - name: Build application
        run: pnpm run build
